spring.application.name=production-based-features-demo
spring.datasource.url=jdbc:mysql://localhost:3306/production-ready-db?useSSL=false
spring.datasource.username=root
spring.datasource.password=mIsty@2810
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
server.port = 9000
employeeService.base.url = http://localhost:8080/
spring.devtools.restart.enabled = true

#logging configuration
logging.level.com.production_based_features.production_based_features.clients.impl=trace
logging.level.com.production_based_features.production_based_features.config=INFO
logging.pattern.console=%d{dd-mm-yyyy hh:MM:ss} [%level] %c{1.} --- %m%n
logging.file.name=application.log
logging.config=classpath:logback-spring.xml

#actuator configuration
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.author=Misty Jangid
info.app.version=1.0.0
management.endpoint.env.show-values=always
management.info.build.enabled=true
management.info.git.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true

#open api doc configuration
springdoc.api-docs.enabled = true
